name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12

      - name: Clone SDL
        run: |
          git clone --depth 1 https://github.com/libsdl-org/SDL.git

      - name: Build with GCC
        run: |
          cmake -D CMAKE_BUILD_TYPE=Debug -B build -S .
          cmake --build build
        working-directory: ${{ github.workspace }}/SDL
        env:
          CC: gcc-12
          CXX: g++-12
